bloom2deb: better diagnostics, export TMPDIR

diff --git a/bloom2deb b/bloom2deb
--- a/bloom2deb
+++ b/bloom2deb
@@ -4,8 +4,15 @@
 
 set -euvx
 
-readonly this="$(readlink -e "$0")"
+readonly this="$(readlink -f "$0")"
 readonly here="$(dirname "${this}")"
+readonly whatami="$(basename "${here}").$(basename "${this}")"
+readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
+
+log() { echo "${whatami}[$$]: $@" >&2; }
+inform() { log "INFO: $@"; }
+warn() { log "WARNING: $@"; }
+error() { log "ERROR: $@"; }
 
 usage() {
     cat <<EOF
@@ -37,10 +44,6 @@ Example:
 EOF
 }
 
-log() { echo "$@" >&2; }
-inform() { log "INFO: $@"; }
-warn() { log "WARNING: $@"; }
-error() { log "ERROR: $@"; }
 die() {
     error "$@"
     usage >&2
@@ -188,6 +191,8 @@ save() {
 #############################
 
 trap cleanup EXIT
+export TMPDIR="${tmpdir}"
+export LC_ALL=C
 
 while getopts ":hrC:V:" opt; do
     case "${opt}" in
