get origtar2debs working again

diff --git a/origtar2debs b/origtar2debs
--- a/origtar2debs
+++ b/origtar2debs
@@ -25,7 +25,6 @@ Bloom, build, and package an orig tarball.
 
 Options
     -h                 print this usage and return success
-    -f                 force bloom (overwrite extant release repository)
     -D DISTRIBUTION    override distribution (default: ${default_distribution})
     -R ROS_DISTRO      override ros_distro (default: ${default_ros_distro})
 
@@ -49,11 +48,8 @@ die() {
 }
 
 cleanup() {
-    status="$?"
-    rm -rf "${tmpdir}"
-    if command -v docker >&2; then
-        docker system prune --force --filter until=6h >&2 || true
-    fi
+    local status="$?"
+    rm -rf "${tmpdir}" || true
     return "${status}"
 }
 
@@ -106,6 +102,94 @@ is_good_origtar() {
     return 0
 }
 
+
+# $1 : ros_distro
+infer_distribution() {
+    case "${1:-}" in
+        kinetic)
+            echo "xenial"
+            return 0
+            ;;
+        melodic)
+            echo "bionic"
+            return 0
+            ;;
+        "")
+            error "undefined ros_distro"
+            return 1
+            ;;
+        *)
+            error "unknown ros_distro: $1"
+            return 1
+            ;;
+    esac
+    return 1
+}
+
+# $1 : distribution
+infer_ros_distro() {
+    case "${1:-}" in
+        xenial)
+            echo "kinetic"
+            return 0
+            ;;
+        bionic)
+            echo "melodic"
+            return 0
+            ;;
+        "")
+            error "undefined distribution"
+            return 1
+            ;;
+        *)
+            error "unknown distribution: $1"
+            return 1
+            ;;
+    esac
+    return 1
+}
+
+# take nothing and detect the OS distribution; print distribution on success;
+# print nothing on failure
+detect_distribution() {
+    if ! [ -f /etc/os-release ]; then
+        error "missing file: /etc/os-release"
+        return 1
+    fi
+    . /etc/os-release
+    if ! [ -n "${UBUNTU_CODENAME:-}" ]; then
+        error "undefined UBUNTU_CODENAME"
+        return 1
+    fi
+    echo "${UBUNTU_CODENAME}"
+    return 0
+}
+
+# take nothing and detect the installed ros_distro; print ros_distro on
+# success; print nothing on failure
+detect_ros_distro() {
+    if ! [ -d /opt/ros ]; then
+        error "missing directory: /opt/ros"
+        return 1
+    fi
+    local ros_distro_list="$(mktemp -t ros.distro.list.XXXXXX)"
+    find /opt/ros -maxdepth 1 -mindepth 1 -type d -exec basename {} \; >"${ros_distro_list}"
+    case "$(wc -l <"${ros_distro_list}")" in
+        0)
+            error "missing ROS installation"
+            return 1
+            ;;
+        1)
+            cat "${ros_distro_list}"
+            return 0
+            ;;
+        *)
+            error "multiple ROS installations"
+            return 1
+            ;;
+    esac
+}
+
 ################################################################################
 
 trap cleanup EXIT
@@ -118,7 +202,6 @@ while getopts ":hfD:R:" opt; do
             usage
             exit "$?"
             ;;
-        f) readonly force_bloom="true" ;;
         D) readonly distribution="${OPTARG}" ;;
         R) readonly ros_distro="${OPTARG}" ;;
         :) die "Missing argument: -${OPTARG}" ;;
@@ -155,139 +238,52 @@ readonly origtar="${origtar}"
 
 # distribution
 if [ -n "${distribution:-}" ]; then
-    info "given distribution: ${distribution}"
+    info "distribution: ${distribution}"
 else
-    readonly distribution="${default_distribution}"
-    warning "defaulting distribution: ${distribution}"
+    if distribution="$(infer_distribution "${ros_distro:-}")"; then
+        warning "inferred distribution for ${ros_distro}: ${distribution}"
+    else
+        if distribution="$(detect_distribution)"; then
+            warning "detected distribution: ${distribution}"
+        else
+            die "failed to assign distribution"
+        fi
+    fi
+    readonly distribution="${distribution}"
 fi
 
 # ros_distro
 if [ -n "${ros_distro:-}" ]; then
-    info "given ros_distro: ${ros_distro}"
+    info "ros_distro: ${ros_distro}"
 else
-    readonly ros_distro="${default_ros_distro}"
-    warning "defaulting ros_distro: ${ros_distro}"
+    if ros_distro="$(infer_ros_distro "${distribution:-}")"; then
+        warning "inferred ros_distro for ${distribution}: ${ros_distro}"
+    else
+        if ros_distro="$(detect_ros_distro)"; then
+            warning "detected ros_distro: ${ros_distro}"
+        else
+            die "failed to assign ros_distro"
+        fi
+    fi
+    readonly ros_distro="${ros_distro}"
 fi
 
 ###################
 # VET OPTIONS END #
 ###################
 
-# assumes `scrippies/git2origtar` creates a well-formed filename
-readonly package_name="$(basename "${origtar%.orig.tar*}" | cut -d_ -f1)"
-readonly real_version="$(basename "${origtar%.orig.tar*}" | cut -d_ -f2)"
-readonly fake_version="$(echo "${real_version}" | cut -d- -f1)"
-readonly release_bare="${PWD}/${package_name}_${real_version}-release.git"
+readonly release_bare="${origtar%.orig.tar*}.git"
+info "$(mkdir -vp "${release_bare}")"
+info "$(git -C "${release_bare}" init --bare)"
 
-readonly origtargz="${origtar%.orig.tar*}.orig.tar.gz"
-case "${origtar}" in
-    *.tar)
-        gzip --no-name -c <"${origtar}" >"${origtargz}"
-        ;;
-    *.tar.bz2)
-        bzip2 -cd <"${origtar}" | gzip --no-name -c >"${origtargz}"
-        ;;
-    *.tar.xz)
-        xz -cd <"${origtar}" | gzip --no-name -c >"${origtargz}"
-        ;;
-    *.tar.gz)
-        if [ "${origtar}" != "${origtargz}" ]; then
-            die "${origtar} != ${origtargz}"
-        fi
-        ;;
-    *)
-        die "bad origtar: ${origtar}"
-        ;;
-esac
+"${here}/origtar2bloom" \
+    -C "${release_bare}" \
+    -R "${ros_distro}" \
+    "${origtar}"
 
-if [ "true" = "${force_bloom:-false}" ] || ! [ -d "${release_bare}" ]; then
-    rm -rf "${release_bare}"
-    mkdir -vp "${release_bare}"
-    info "$(git init --bare "${release_bare}")"
-
-    # > The upstream repository is the repository where you do your development
-    # > and host the source code of your package. This repository can be hosted
-    # > anywhere (even locally) and can be a git, hg, or svn repository or the
-    # > location of an archive (tar.gz only for now, but there are plans for
-    # > tar.bz and zip).
-    #
-    # --- http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease#Preparing_for_Release
-    "${here}/tarball2bloom" \
-        -C "${release_bare}" \
-        -R "${ros_distro}" \
-        -P "${package_name}" \
-        -V "${fake_version}" \
-        "${origtargz}"
-else
-    warning "skipping tarball2bloom"
-fi
-
-readonly branch_list="${release_bare%.git}.branch.list"
-(
-    cd "$(mktemp -d)"
-    git clone "file://${release_bare}" .
-    git branch -a
-) >"${branch_list}"
-
-# > [a package name] must only consist of alphanumerics and _ separators
-#
-# -- http://www.ros.org/reps/rep-0144.html#mandatory-rules
-#
-# ..._*BUT*_ catkin will happily build packages with hyphens, too.
-sed -nri "s|^  remotes/origin/(debian/${ros_distro}/${distribution}/[[:alnum:]_-]+)$|\1|gp" "${branch_list}"
-sort -uo "${branch_list}" "${branch_list}"
-
-# uncomment this to avoid "*_example" subprojects
-#sed -ri '/.*_examples$/d' "${branch_list}"
-
-# create dependency list, topo sort, and reverse topo sort
-(
-    cd "$(mktemp -d)"
-    tar -xf "${origtargz}"
-    "${here}/rosdeps"
-) >rosdeps.out
-
-readonly release_dir="${release_bare%.git}.dir"
-
-# `bloom2deb` creates a file-local apt repository with `Packages` and `Sources`
-# files in the current working directory.
-touch Packages Sources
-while read package; do
-    dpkg_name="$(echo "ros-${ros_distro}-${package}" | tr '_' '-')"
-    if ! branch_name="$(grep -E "${package}\$" <"${branch_list}")"; then
-        die "package missing branch: ${package}"
-    fi
-    sed -nr 's/^(Package|Version): (.*)$/\2/gp' Packages | xargs -L2 >packages.list
-    sed -nr 's/^(Package|Version): (.*)$/\2/gp' Sources | xargs -L2 >sources.list
-    if extant_package="$(grep "^${dpkg_name} ${real_version}" packages.list)"; then
-        info "extant package: ${extant_package}"
-    fi
-    if extant_source="$(grep "^${dpkg_name} ${real_version}" sources.list)"; then
-        info "extant source: ${extant_source}"
-    fi
-    if [ -n "${extant_package:-}" ] && [ -n "${extant_source:-}" ]; then
-        warning "skipping bloom2deb: ${dpkg_name} ${real_version}"
-        continue
-    fi
-    info "starting bloom2deb: ${dpkg_name} ${real_version}"
-
-    # because bloom hates git-lfs or something
-    rm -rf "${release_dir}"
-    mkdir -vp "${release_dir}"
-    git clone --branch "${branch_name}" "file://${release_bare}" "${release_dir}"
-
-    # this is where we override the bloom-release version
-    "${here}/bloom2deb" -C "${release_dir}" -V "${real_version}"
-    info "SUCCESS: BUILT branch ${branch_name}, version ${real_version}"
-
-    rm -rf "${release_dir}"
-done <rosdeps.out
-
-info "SUCCESS: PACKAGED ${origtar}"
-info "real_version : ${real_version}"
-info "fake_version : ${fake_version}"
-info "release_bare : ${release_bare}"
-info "ros_distro   : ${ros_distro}"
-info "distribution : ${distribution}"
+"${here}/bloom2debs" \
+    -C "${release_bare}" \
+    -D "${distribution}" \
+    -R "${ros_distro}"
 
 exit "$?"
